### ISSUE TITLE
Reducing creditline limits should always be possible

### ISSUE THREAD

**Issue by ice09** [trustlines-network/contracts#34]
Currently it is not possible to reduce the `creditline` below `balance`, ie. if Alice owes Bob 10 IOUs, Bob cannot reduce the `creditline` given to Alice below the `balance` of 10. 

This should be possible with this logic:

If the debtor initiates a transfer which _reduces_ the `balance` towards the lower `creditline` this should be possible, to enable the debtor to reduce his debt.

# Example

Alice owes to Bob 10 IOUs (so the `balance` is 10) and the `creditline` from Bob to Alice is 10. Currently, Bob cannot lower this `creditline`, but Bob should be able to set the `creditline` to 5, preventing Alice from doing transfers which increase Alice's `balance` but allowing for Alice to reduce the `balance` from 10 to 5 (or 6-9).

**Comment by heikoheiko** [comment]
Assuming the requested functionality is, that a creditor can reduce the creditline of the debtor below the current debt. In order to do so, the creditor spends balance he has with the creditor such that after the transfer another of his trustlines owes him the money. As the imbalance was reduced he can then close reduce or close the trustline. 

Please see the "Closing a Trustline" issue which uses this technique (needs to be created. Note: here we'd like to spend an exact amount instead to receive an exact amount, so that the balance of the initiating trustline is exactly zero, how to?).

**Comment by heikoheiko** [comment]
Q: Do we need to support reducing creditlines below the balance if there is no sufficient capacity to do a triangular transfer?

**Comment by ice09** [comment]
For this issue there exist two different solutions, which one should be supported?

1. The balance is "rebalanced" as described above (triangular transfer)
2. The balance can just not be increased, but the debt can always be reduced until the balance is below the creditline again

**Comment by heikoheiko** [comment]
1. should be supported. but this is not related to the smart contracts, but rather to the client requesting a transfer, which reduces the imbalance from the relay server. 
2. I think the creditline should be reducable to any value, independent of the balance. note, that interest still needs to be updatable.

**Comment by heikoheiko** [comment]
Please update issue, to be clear, that it's about credit line *limits* not interest.
